FROM node:alpine
COPY . /doc
CMD node /doc/index.js 

#//docker --version
#//node index.js
#//docker build -t doc .
#//docker images
# docker pull openjdk
# docker run --name om -it -d openjdk
# docker ps
# docker exec -it om jshell
# System.out.println("Hello");